export type Club = {
  name: string;
  primaryHex: string;
  secondaryHex: string;
  stadium: string;
  league: string;
};

export const ALL_FOOTBALL_CLUBS: Club[] = [
  // Premier League
  { name: "Arsenal", primaryHex: "#EF0107", secondaryHex: "#FFFFFF", stadium: "Emirates Stadium", league: "Premier League" },
  { name: "Aston Villa", primaryHex: "#670E36", secondaryHex: "#95BFE5", stadium: "Villa Park", league: "Premier League" },
  { name: "AFC Bournemouth", primaryHex: "#DA291C", secondaryHex: "#000000", stadium: "Vitality Stadium", league: "Premier League" },
  { name: "Brentford", primaryHex: "#E30613", secondaryHex: "#000000", stadium: "Gtech Community Stadium", league: "Premier League" },
  { name: "Brighton & Hove Albion", primaryHex: "#0057B8", secondaryHex: "#FFFFFF", stadium: "Amex Stadium", league: "Premier League" },
  { name: "Burnley", primaryHex: "#6C1D45", secondaryHex: "#99D6EA", stadium: "Turf Moor", league: "Premier League" },
  { name: "Chelsea", primaryHex: "#034694", secondaryHex: "#DBA111", stadium: "Stamford Bridge", league: "Premier League" },
  { name: "Crystal Palace", primaryHex: "#1B458F", secondaryHex: "#C4122E", stadium: "Selhurst Park", league: "Premier League" },
  { name: "Everton", primaryHex: "#003399", secondaryHex: "#FFFFFF", stadium: "Goodison Park", league: "Premier League" },
  { name: "Fulham", primaryHex: "#CC0000", secondaryHex: "#000000", stadium: "Craven Cottage", league: "Premier League" },
  { name: "Leeds United", primaryHex: "#FFCD00", secondaryHex: "#1D428A", stadium: "Elland Road", league: "Premier League" },
  { name: "Liverpool", primaryHex: "#C8102E", secondaryHex: "#00B2A9", stadium: "Anfield", league: "Premier League" },
  { name: "Manchester City", primaryHex: "#6CABDD", secondaryHex: "#1C2C5B", stadium: "Etihad Stadium", league: "Premier League" },
  { name: "Manchester United", primaryHex: "#DA020E", secondaryHex: "#FBE122", stadium: "Old Trafford", league: "Premier League" },
  { name: "Newcastle United", primaryHex: "#241F20", secondaryHex: "#FFFFFF", stadium: "St. James' Park", league: "Premier League" },
  { name: "Nottingham Forest", primaryHex: "#DD0000", secondaryHex: "#FFFFFF", stadium: "City Ground", league: "Premier League" },
  { name: "Sunderland", primaryHex: "#EB172B", secondaryHex: "#000000", stadium: "Stadium of Light", league: "Premier League" },
  { name: "Tottenham Hotspur", primaryHex: "#132257", secondaryHex: "#FFFFFF", stadium: "Tottenham Hotspur Stadium", league: "Premier League" },
  { name: "West Ham United", primaryHex: "#7A263A", secondaryHex: "#1BB1E7", stadium: "London Stadium", league: "Premier League" },
  { name: "Wolverhampton Wanderers", primaryHex: "#FDB913", secondaryHex: "#231F20", stadium: "Molineux Stadium", league: "Premier League" },
  // Championship
  { name: "Birmingham City", primaryHex: "#0000FF", secondaryHex: "#FFFFFF", stadium: "St Andrew's", league: "Championship" },
  { name: "Blackburn Rovers", primaryHex: "#009EE0", secondaryHex: "#FFFFFF", stadium: "Ewood Park", league: "Championship" },
  { name: "Bristol City", primaryHex: "#E3001B", secondaryHex: "#FFFFFF", stadium: "Ashton Gate", league: "Championship" },
  { name: "Charlton Athletic", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "The Valley", league: "Championship" },
  { name: "Coventry City", primaryHex: "#59CBE8", secondaryHex: "#034694", stadium: "Coventry Building Society Arena", league: "Championship" },
  { name: "Derby County", primaryHex: "#161615", secondaryHex: "#FFFFFF", stadium: "Pride Park", league: "Championship" },
  { name: "Hull City", primaryHex: "#F5A12D", secondaryHex: "#000000", stadium: "MKM Stadium", league: "Championship" },
  { name: "Ipswich Town", primaryHex: "#0044A9", secondaryHex: "#FFFFFF", stadium: "Portman Road", league: "Championship" },
  { name: "Leicester City", primaryHex: "#003090", secondaryHex: "#FDBE11", stadium: "King Power Stadium", league: "Championship" },
  { name: "Middlesbrough", primaryHex: "#E41B17", secondaryHex: "#FFFFFF", stadium: "Riverside Stadium", league: "Championship" },
  { name: "Millwall", primaryHex: "#001D5E", secondaryHex: "#FFFFFF", stadium: "The Den", league: "Championship" },
  { name: "Norwich City", primaryHex: "#00A650", secondaryHex: "#FFF200", stadium: "Carrow Road", league: "Championship" },
  { name: "Oxford United", primaryHex: "#F9A01B", secondaryHex: "#000000", stadium: "Kassam Stadium", league: "Championship" },
  { name: "Portsmouth", primaryHex: "#001489", secondaryHex: "#FFFFFF", stadium: "Fratton Park", league: "Championship" },
  { name: "Preston North End", primaryHex: "#001A57", secondaryHex: "#FFFFFF", stadium: "Deepdale", league: "Championship" },
  { name: "Queens Park Rangers", primaryHex: "#1D5BA4", secondaryHex: "#FFFFFF", stadium: "Loftus Road", league: "Championship" },
  { name: "Sheffield United", primaryHex: "#EE2737", secondaryHex: "#000000", stadium: "Bramall Lane", league: "Championship" },
  { name: "Sheffield Wednesday", primaryHex: "#003082", secondaryHex: "#FFFFFF", stadium: "Hillsborough Stadium", league: "Championship" },
  { name: "Southampton", primaryHex: "#D71920", secondaryHex: "#FFFFFF", stadium: "St Mary's Stadium", league: "Championship" },
  { name: "Stoke City", primaryHex: "#E03A3E", secondaryHex: "#1B449C", stadium: "bet365 Stadium", league: "Championship" },
  { name: "Swansea City", primaryHex: "#121212", secondaryHex: "#FFFFFF", stadium: "Swansea.com Stadium", league: "Championship" },
  { name: "Watford", primaryHex: "#FBEE23", secondaryHex: "#ED2127", stadium: "Vicarage Road", league: "Championship" },
  { name: "West Bromwich Albion", primaryHex: "#122F67", secondaryHex: "#FFFFFF", stadium: "The Hawthorns", league: "Championship" },
  { name: "Wrexham", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "Racecourse Ground", league: "Championship" },
  // League One
  { name: "AFC Wimbledon", primaryHex: "#0000FF", secondaryHex: "#FFFF00", stadium: "Cherry Red Records Stadium", league: "League One" },
  { name: "Barnsley", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "Oakwell Stadium", league: "League One" },
  { name: "Blackpool", primaryHex: "#F68712", secondaryHex: "#FFFFFF", stadium: "Bloomfield Road", league: "League One" },
  { name: "Bolton Wanderers", primaryHex: "#001F5B", secondaryHex: "#FFFFFF", stadium: "Toughsheet Community Stadium", league: "League One" },
  { name: "Bradford City", primaryHex: "#862633", secondaryHex: "#F5A12D", stadium: "Valley Parade", league: "League One" },
  { name: "Burton Albion", primaryHex: "#F5A12D", secondaryHex: "#000000", stadium: "Pirelli Stadium", league: "League One" },
  { name: "Cardiff City", primaryHex: "#0070B5", secondaryHex: "#FFFFFF", stadium: "Cardiff City Stadium", league: "League One" },
  { name: "Doncaster Rovers", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "Eco-Power Stadium", league: "League One" },
  { name: "Exeter City", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "St James Park", league: "League One" },
  { name: "Huddersfield Town", primaryHex: "#0E63AD", secondaryHex: "#FFFFFF", stadium: "John Smith's Stadium", league: "League One" },
  { name: "Leyton Orient", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "Brisbane Road", league: "League One" },
  { name: "Lincoln City", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "LNER Stadium", league: "League One" },
  { name: "Luton Town", primaryHex: "#F78F1E", secondaryHex: "#FFFFFF", stadium: "Kenilworth Road", league: "League One" },
  { name: "Mansfield Town", primaryHex: "#F5A12D", secondaryHex: "#003087", stadium: "One Call Stadium", league: "League One" },
  { name: "Northampton Town", primaryHex: "#862633", secondaryHex: "#FFFFFF", stadium: "Sixfields Stadium", league: "League One" },
  { name: "Peterborough United", primaryHex: "#1D5BA4", secondaryHex: "#FFFFFF", stadium: "Weston Homes Stadium", league: "League One" },
  { name: "Plymouth Argyle", primaryHex: "#00543D", secondaryHex: "#FFFFFF", stadium: "Home Park", league: "League One" },
  { name: "Port Vale", primaryHex: "#1A1A1A", secondaryHex: "#FFCD00", stadium: "Vale Park", league: "League One" },
  { name: "Reading", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "Select Car Leasing Stadium", league: "League One" },
  { name: "Rotherham United", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "AESSEAL New York Stadium", league: "League One" },
  { name: "Stevenage", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "Broadhall Way", league: "League One" },
  { name: "Stockport County", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "Edgeley Park", league: "League One" },
  { name: "Wigan Athletic", primaryHex: "#1D5BA4", secondaryHex: "#FFFFFF", stadium: "DW Stadium", league: "League One" },
  { name: "Wycombe Wanderers", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "Adams Park", league: "League One" },
  // League Two
  { name: "Accrington Stanley", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "Crown Ground", league: "League Two" },
  { name: "Barnet", primaryHex: "#F5A12D", secondaryHex: "#000000", stadium: "The Hive Stadium", league: "League Two" },
  { name: "Barrow", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "Holker Street", league: "League Two" },
  { name: "Bristol Rovers", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "Memorial Stadium", league: "League Two" },
  { name: "Bromley", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "Hayes Lane", league: "League Two" },
  { name: "Cambridge United", primaryHex: "#F5A12D", secondaryHex: "#000000", stadium: "Abbey Stadium", league: "League Two" },
  { name: "Cheltenham Town", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "Whaddon Road", league: "League Two" },
  { name: "Chesterfield", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "SMH Group Stadium", league: "League Two" },
  { name: "Colchester United", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "Colchester Community Stadium", league: "League Two" },
  { name: "Crawley Town", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "Broadfield Stadium", league: "League Two" },
  { name: "Crewe Alexandra", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "Gresty Road", league: "League Two" },
  { name: "Fleetwood Town", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "Highbury Stadium", league: "League Two" },
  { name: "Gillingham", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "Priestfield Stadium", league: "League Two" },
  { name: "Grimsby Town", primaryHex: "#CC0000", secondaryHex: "#000000", stadium: "Blundell Park", league: "League Two" },
  { name: "Harrogate Town", primaryHex: "#F5A12D", secondaryHex: "#000000", stadium: "Wetherby Road", league: "League Two" },
  { name: "Milton Keynes Dons", primaryHex: "#FFFF00", secondaryHex: "#000000", stadium: "Stadium MK", league: "League Two" },
  { name: "Newport County", primaryHex: "#F5A12D", secondaryHex: "#000000", stadium: "Rodney Parade", league: "League Two" },
  { name: "Notts County", primaryHex: "#1A1A1A", secondaryHex: "#FFFFFF", stadium: "Meadow Lane", league: "League Two" },
  { name: "Oldham Athletic", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "Boundary Park", league: "League Two" },
  { name: "Salford City", primaryHex: "#CC0000", secondaryHex: "#000000", stadium: "Moor Lane", league: "League Two" },
  { name: "Shrewsbury Town", primaryHex: "#003087", secondaryHex: "#F5A12D", stadium: "New Meadow", league: "League Two" },
  { name: "Swindon Town", primaryHex: "#CC0000", secondaryHex: "#FFFFFF", stadium: "County Ground", league: "League Two" },
  { name: "Tranmere Rovers", primaryHex: "#003087", secondaryHex: "#FFFFFF", stadium: "Prenton Park", league: "League Two" },
  { name: "Walsall", primaryHex: "#CC0000", secondaryHex: "#000000", stadium: "Bescot Stadium", league: "League Two" },
];

export const allClubForName = (name: string): Club | undefined =>
  ALL_FOOTBALL_CLUBS.find(c => c.name.toLowerCase() === name.toLowerCase());

export const allStadiumForClub = (name: string): string | undefined =>
  ALL_FOOTBALL_CLUBS.find(c => c.name.toLowerCase() === name.toLowerCase())?.stadium;