export const CLUB_LEAGUES: Record<string, string> = {
  // Premier League
  "Arsenal": "Premier League",
  "Aston Villa": "Premier League",
  "AFC Bournemouth": "Premier League",
  "Brentford": "Premier League",
  "Brighton & Hove Albion": "Premier League",
  "Burnley": "Premier League",
  "Chelsea": "Premier League",
  "Crystal Palace": "Premier League",
  "Everton": "Premier League",
  "Fulham": "Premier League",
  "Leeds United": "Premier League",
  "Liverpool": "Premier League",
  "Manchester City": "Premier League",
  "Manchester United": "Premier League",
  "Newcastle United": "Premier League",
  "Nottingham Forest": "Premier League",
  "Sunderland": "Premier League",
  "Tottenham Hotspur": "Premier League",
  "West Ham United": "Premier League",
  "Wolverhampton Wanderers": "Premier League",
  // Championship
  "Birmingham City": "Championship",
  "Blackburn Rovers": "Championship",
  "Bristol City": "Championship",
  "Charlton Athletic": "Championship",
  "Coventry City": "Championship",
  "Derby County": "Championship",
  "Hull City": "Championship",
  "Ipswich Town": "Championship",
  "Leicester City": "Championship",
  "Middlesbrough": "Championship",
  "Millwall": "Championship",
  "Norwich City": "Championship",
  "Oxford United": "Championship",
  "Portsmouth": "Championship",
  "Preston North End": "Championship",
  "Queens Park Rangers": "Championship",
  "Sheffield United": "Championship",
  "Sheffield Wednesday": "Championship",
  "Southampton": "Championship",
  "Stoke City": "Championship",
  "Swansea City": "Championship",
  "Watford": "Championship",
  "West Bromwich Albion": "Championship",
  "Wrexham": "Championship",
  // League One
  "AFC Wimbledon": "League One",
  "Barnsley": "League One",
  "Blackpool": "League One",
  "Bolton Wanderers": "League One",
  "Bradford City": "League One",
  "Burton Albion": "League One",
  "Cardiff City": "League One",
  "Doncaster Rovers": "League One",
  "Exeter City": "League One",
  "Huddersfield Town": "League One",
  "Leyton Orient": "League One",
  "Lincoln City": "League One",
  "Luton Town": "League One",
  "Mansfield Town": "League One",
  "Northampton Town": "League One",
  "Peterborough United": "League One",
  "Plymouth Argyle": "League One",
  "Port Vale": "League One",
  "Reading": "League One",
  "Rotherham United": "League One",
  "Stevenage": "League One",
  "Stockport County": "League One",
  "Wigan Athletic": "League One",
  "Wycombe Wanderers": "League One",
  // League Two
  "Accrington Stanley": "League Two",
  "Barnet": "League Two",
  "Barrow": "League Two",
  "Bristol Rovers": "League Two",
  "Bromley": "League Two",
  "Cambridge United": "League Two",
  "Cheltenham Town": "League Two",
  "Chesterfield": "League Two",
  "Colchester United": "League Two",
  "Crawley Town": "League Two",
  "Crewe Alexandra": "League Two",
  "Fleetwood Town": "League Two",
  "Gillingham": "League Two",
  "Grimsby Town": "League Two",
  "Harrogate Town": "League Two",
  "Milton Keynes Dons": "League Two",
  "Newport County": "League Two",
  "Notts County": "League Two",
  "Oldham Athletic": "League Two",
  "Salford City": "League Two",
  "Shrewsbury Town": "League Two",
  "Swindon Town": "League Two",
  "Tranmere Rovers": "League Two",
  "Walsall": "League Two",
};

export const LEAGUES = ["Premier League", "Championship", "League One", "League Two"];

export const getLeagueForTeam = (team: string): string => {
  return CLUB_LEAGUES[team] ?? "Other";
};