export const EFL_STADIUM_MAP: Record<string, string> = {
  // Championship
  "Birmingham City": "St Andrew's",
  "Blackburn Rovers": "Ewood Park",
  "Bristol City": "Ashton Gate",
  "Charlton Athletic": "The Valley",
  "Coventry City": "Coventry Building Society Arena",
  "Derby County": "Pride Park",
  "Hull City": "MKM Stadium",
  "Ipswich Town": "Portman Road",
  "Leicester City": "King Power Stadium",
  "Middlesbrough": "Riverside Stadium",
  "Millwall": "The Den",
  "Norwich City": "Carrow Road",
  "Oxford United": "Kassam Stadium",
  "Portsmouth": "Fratton Park",
  "Preston North End": "Deepdale",
  "Queens Park Rangers": "Loftus Road",
  "Sheffield United": "Bramall Lane",
  "Sheffield Wednesday": "Hillsborough Stadium",
  "Southampton": "St Mary's Stadium",
  "Stoke City": "bet365 Stadium",
  "Swansea City": "Swansea.com Stadium",
  "Watford": "Vicarage Road",
  "West Bromwich Albion": "The Hawthorns",
  "Wrexham": "Racecourse Ground",
  // League One
  "AFC Wimbledon": "Cherry Red Records Stadium",
  "Barnsley": "Oakwell Stadium",
  "Blackpool": "Bloomfield Road",
  "Bolton Wanderers": "Toughsheet Community Stadium",
  "Bradford City": "Valley Parade",
  "Burton Albion": "Pirelli Stadium",
  "Cardiff City": "Cardiff City Stadium",
  "Doncaster Rovers": "Eco-Power Stadium",
  "Exeter City": "St James Park",
  "Huddersfield Town": "John Smith's Stadium",
  "Leyton Orient": "Brisbane Road",
  "Lincoln City": "LNER Stadium",
  "Luton Town": "Kenilworth Road",
  "Mansfield Town": "One Call Stadium",
  "Northampton Town": "Sixfields Stadium",
  "Peterborough United": "Weston Homes Stadium",
  "Plymouth Argyle": "Home Park",
  "Port Vale": "Vale Park",
  "Reading": "Select Car Leasing Stadium",
  "Rotherham United": "AESSEAL New York Stadium",
  "Stevenage": "Broadhall Way",
  "Stockport County": "Edgeley Park",
  "Wigan Athletic": "DW Stadium",
  "Wycombe Wanderers": "Adams Park",
  // League Two
  "Accrington Stanley": "Crown Ground",
  "Barnet": "The Hive Stadium",
  "Barrow": "Holker Street",
  "Bristol Rovers": "Memorial Stadium",
  "Bromley": "Hayes Lane",
  "Cambridge United": "Abbey Stadium",
  "Cheltenham Town": "Whaddon Road",
  "Chesterfield": "SMH Group Stadium",
  "Colchester United": "Colchester Community Stadium",
  "Crawley Town": "Broadfield Stadium",
  "Crewe Alexandra": "Gresty Road",
  "Fleetwood Town": "Highbury Stadium",
  "Gillingham": "Priestfield Stadium",
  "Grimsby Town": "Blundell Park",
  "Harrogate Town": "Wetherby Road",
  "Milton Keynes Dons": "Stadium MK",
  "Newport County": "Rodney Parade",
  "Notts County": "Meadow Lane",
  "Oldham Athletic": "Boundary Park",
  "Salford City": "Moor Lane",
  "Shrewsbury Town": "New Meadow",
  "Swindon Town": "County Ground",
  "Tranmere Rovers": "Prenton Park",
  "Walsall": "Bescot Stadium",
};

export const eflStadiumForClub = (club: string): string | null => {
  return EFL_STADIUM_MAP[club] ?? null;
};